### ISSUE TITLE
 Error creating shaded jar: invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by DennisRoeck** [eclipse/xtext#1204] opened 2018-05-10 10:31 UTC
Windows10/Java9/Maven/Fat Jar/JUnit5

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.xtext.example.mydsl.parent 1.0.0-SNAPSHOT ...... SUCCESS [  0.261 s]
[INFO] org.xtext.example.mydsl ............................ SUCCESS [ 28.587 s]
[INFO] org.xtext.example.mydsl.ide ........................ FAILURE [  4.870 s]
[INFO] org.xtext.example.mydsl.ui ......................... SKIPPED
[INFO] org.xtext.example.mydsl.target ..................... SKIPPED
[INFO] org.xtext.example.mydsl.feature .................... SKIPPED
[INFO] org.xtext.example.mydsl.repository ................. SKIPPED
[INFO] org.xtext.example.mydsl.tests ...................... SKIPPED
[INFO] org.xtext.example.mydsl.ui.tests 1.0.0-SNAPSHOT .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 min
[INFO] Finished at: 2018-05-10T11:19:16+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project org.xtext.example.mydsl.ide: Error creating shaded jar: ZipFile invalid LOC header (bad signature) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.xtext.example.mydsl.ide

**Comment by cdietrich** [comment] 2018-05-10 10:53
again an issue i could not reproduce.
i wonder which jar it actually complains about. can you rerun with -X

**Comment by cdietrich** [comment] 2018-05-18 05:03
@DennisRoeck  any news on that. still cannot reproduce

**Comment by kthoms** [comment] 2018-05-18 06:50
He is on vacation now.

**Comment by DennisRoeck** [comment] 2018-05-18 07:17
i can still reproduce this problem anytime.

**Comment by cdietrich** [comment] 2018-05-21 17:22
@DennisRoeck did you try that with a clean maven repo
@kthoms could you reproduce this. i could not on several machines

**Comment by cdietrich** [comment] 2018-05-22 18:46
ping

**Comment by JanK411** [comment] 2018-05-24 20:59
well, I had exactly the same issue (on a Java-8 Xtext(2.13)-Project) and tried several things without success.
Now I was very depressed, deleted my .m2-Folder, reopened my project, updated all my Maven-Projects, did a clean install and everything seems to be fine.
Just so you know. ¯\_(ツ)_/¯

**Comment by kthoms** [comment] 2018-05-27 21:50
@DennisRoeck So please clean up ~/.m2/repository.
Closing, looks as this is a local problem.

**Closed by kthoms** 2018-05-27 21:50 UTC

**Comment by PremPal-REISysIn** [comment] 2018-10-09 09:31
Faced the same issue and followed the above comment. Once I cleaned up ~/.m2/repository. This error was resolved.

**Comment by peter-wang-wsl** [comment] 2019-03-13 06:25
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.1
:shade (default) on project hdfs-ftp-server: Error creating shaded jar: invalid
LOC header (bad signature) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-shade-plugin:2.4.1:shade (default) on project hdfs
-ftp-server: Error creating shaded jar: invalid LOC header (bad signature)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBu
ild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded
 jar: invalid LOC header (bad signature)
        at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:
539)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:209)
        ... 19 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
        at java.util.zip.ZipFile.read(Native Method)
        at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
        at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:41
9)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:189)
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:175)
        at org.apache.maven.plugins.shade.DefaultShader.addResource(DefaultShade
r.java:478)
        at org.apache.maven.plugins.shade.DefaultShader.shade(DefaultShader.java
:167)
        at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:
454)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

@cdietrich above is my error log, please identify it without clean up ~/.m2/repository. Thank you.

**Comment by invzbl3** [comment] 2019-08-13 19:12
I had this type of issue:
Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project: Error creating shaded jar: invalid LOC header (bad signature)

because of:
error reading \.m2\repository\org\jsoup\jsoup\1.11.3\jsoup-1.11.3.jar; invalid LOC header (bad signature)

I had the same jar which was genereted by jsoup dependency not webdrivermanager.
When I deleted from jsoup and recreated by your lib (which will be recreated during packaging), this issue was solved.
