### ISSUE TITLE
Newly created xtext project doesn't run validators in unit tests

### ISSUE THREAD

**Issue by TomCLForwood** [eclipse/xtext#1930] opened 2021-02-03 12:59 UTC
Using Eclipse 2020-12 and Xtext 2.24.0

Reproduction

- I ran the create new xtext project wizard with all default options.
- I then ran the mwe2 to generate all the artifacts
- In the generated MyDSLValidator I uncommented the checkGreetingStartsWithCapital check and added the imports
- In MyDslParsingTest I injected a ValidationTestHelper, changed the greeting in the test to "Hello xtext!" and asserted that the warning was raised

I expected that the validator would be run, raising a warning saying that the greeting must start with a capital letter and the test assertion will pass. 
Instead the code in the validator was never called (confirmed with breakpoints) and tests failed as the warning assertion

The validation does work successfully when running the Runtime eclipse.

The same issue is seen on windows and MacOS

The generated projects are attached

[mydsl.zip](https://github.com/eclipse/xtext/files/5918535/mydsl.zip)

**Comment by cdietrich** [comment] 2021-02-03 13:02
might be dupe of https://github.com/eclipse/xtext-core/issues/1648

**Comment by cdietrich** [comment] 2021-02-08 11:22
@miklossy any update here?

**Comment by miklossy** [comment] 2021-02-10 06:45
I can reproduce the problem with `Eclipse 2020-12` and `Xtext 2.24.0`.
![screencast](https://user-images.githubusercontent.com/20393472/107475076-d7bf9480-6b73-11eb-9098-13a91dcb5493.gif)


However, it works fine when using `Eclipse 2020-12` and `Xtext 2.25.0`. (not released yet).
![screencast2](https://user-images.githubusercontent.com/20393472/107475095-ddb57580-6b73-11eb-802d-92fea88313d7.gif)


Seems that it is really a duplicate of https://github.com/eclipse/xtext-core/issues/1648

@TomCLForwood : Could you please try it out using Xtext latest and give us feedback?
You can install it into Eclipse from the `https://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest/` update site.

**Comment by cdietrich** [comment] 2021-02-15 12:15
i consider this fixed in 2.25. If you still find problems, feel free to reopen @TomCLForwood

**Closed by cdietrich** 2021-02-15 12:15 UTC
