### ISSUE TITLE
Xtext v2.32.0: `com.google.inject`: Missing Constraint: Import-Package:  `sun.misc`; version="0.0.0"

### ISSUE THREAD

**Issue by maxkratz** [eclipse/xtext#2800] opened 2023-09-11 11:22 UTC
Similar to https://github.com/eclipse/xtext/issues/2717, Xtext **v2.32.0** breaks Eclipse Modeling in version **2023-06**.
This means that the default installation of the latest stable Eclipse Modeling with the latest stable release of Xtext is currently broken.

Steps to reproduce:
- Download Eclipse Modeling version 2023-06, e.g., from here: https://ftp.fau.de/eclipse/technology/epp/downloads/release/2023-06/R/
- Install Xtext v2.32.0, e.g., from this update site: http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
- Try to start a runtime Eclipse and see the error message:

![image](https://github.com/eclipse/xtext/assets/20956405/2078d544-710b-4a73-96f8-fc0c44327697)

**Comment by szarnekow** [comment] 2023-09-11 11:26
@HannesWell can you share your thoughts on this, please?

**Comment by cdietrich** [comment] 2023-09-11 11:47
this is a pde issue that is fixed in 202309 
https://github.com/eclipse-pde/eclipse.pde/issues/429

**Comment by szarnekow** [comment] 2023-09-11 11:51
@maxkratz Can you confirm that the problem is no longer reproducible when you start from 2023-09 ?

**Comment by maxkratz** [comment] 2023-09-11 12:59
> @maxkratz Can you confirm that the problem is no longer reproducible when you start from 2023-09 ?

Yes, I can confirm that the problem is not reproducible in Eclipse Modeling 2023-09.

If I understand [this page](https://wiki.eclipse.org/Simultaneous_Release) correctly, the 2023-09 release is planned for the 13th of September, so the problem will be fixed in two days :).

**Comment by szarnekow** [comment] 2023-09-11 13:01
Thank you for the report and the timely evaluation of 2023-09 to confirming the fix! I'll close this issue.

**Closed by szarnekow** 2023-09-11 13:01 UTC

**Comment by HannesWell** [comment] 2023-09-11 17:49
> this is a pde issue that is fixed in 202309 [eclipse-pde/eclipse.pde#429](https://github.com/eclipse-pde/eclipse.pde/issues/429)

Yes, I can only confirm this.

I also use Eclipse-Modelling 2023-09 with the Xtext 2.32 in the TP and since the the mentioned fix in PDE was available the error vanished as expected. With 2023-09 pre M3 and Xtext 2.32 nightly builds I encountered it, so it should be really fixed.

**Comment by HannesWell** [comment] 2023-09-11 17:54
> If I understand [this page](https://wiki.eclipse.org/Simultaneous_Release) correctly, the 2023-09 release is planned for the 13th of September, so the problem will be fixed in two days :).

That's correct.
You can always find Milestones and Release-Candidates of future releases here under the first entry:
https://www.eclipse.org/downloads/packages/release/
There is also a `latest` Product-Version stream for Oomph.

In general testing future release before they are released is more than welcome in order to find regressions as early as possible.
