### ISSUE TITLE
Antlr not found in building plain Maven project for LS

### ISSUE THREAD

**Issue by UdoW** [eclipse/xtext#1235] opened 2018-07-05 09:34 UTC
I created a new Xtext project with the project wizard.
I created a language server project with Maven as the build engine.

The creation worked fine but when I tried to build it I got the Antlr error messages.
The error message explains that I have to copy the file .antlr-generator-3.2.0-patch.jar next to my DSL project but this is not true with this Maven build layout.

You have to put the file in the parent project, i.e. &lt;dsl-package-name&gt;.parent. I.e. that Maven project from which you start the build.

**Comment by cdietrich** [comment] 2018-07-05 09:42
what do you mean by "trx to build"
call maven?
call workflow?
are you off or online?

**Comment by cdietrich** [comment] 2018-07-05 09:42
which options did you exaclty select in the wizard?

**Comment by cdietrich** [comment] 2018-07-05 09:43
am not sure if we can detect the layout at the place where this message is created.
we have way to many options and combinations.
so i would consider that as wontfix
@kthoms @szarnekow what do you think?

**Comment by UdoW** [comment] 2018-07-05 09:46
I called mvn clean install.
I am behind a proxy.
Then I remembered to put the antlr Jar to some place in the project. But it is not the same place as when you build it with Tycho.

**Comment by cdietrich** [comment] 2018-07-05 09:47
yes it depends on the layout.
but i dont want to add a 5 page error mesages that covers all possibilities one could imagine

**Comment by szarnekow** [comment] 2018-07-05 10:22
@UdoW Adding a maven dep to antlr / add it to the target platform should to issue for you. Unfortunately we cannot do this in Xtext itself.

**Comment by UdoW** [comment] 2018-07-05 11:15
I already added this

		
		<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>antlr-runtime</artifactId>
			<version>3.2</version>
		</dependency>

to the other dependencies in the DSL project but it had no effect.

**Comment by cdietrich** [comment] 2018-07-30 11:35
@UdoW can you try to use http://search.maven.org/remotecontent?filepath=org/xtext/antlr-generator/3.2.1/antlr-generator-3.2.1.pom

**Comment by cdietrich** [comment] 2018-08-07 09:38
@UdoW any news on this issue?

**Comment by cdietrich** [comment] 2018-08-13 09:18
we had a look, that class misses the `de.itemis.xtext.antlr.toolrunner.AntlrToolRunner` class
=> the only option currently is to check in the `.antlr-generator-3.2.0-patch.jar` file

**Comment by cdietrich** [comment] 2018-08-13 10:26
=> class is contained in

```
<dependency>
  <groupId>org.eclipse.xtext</groupId>
  <artifactId>xtext-antlr-generator</artifactId>
  <version>2.1.1</version>
</dependency>
```

**Comment by cdietrich** [comment] 2018-08-31 08:52
ping @UdoW

**Comment by cdietrich** [comment] 2018-10-26 08:30
I will close this as works for me now. feel free to reopen is you have a reproducible usecase

**Closed by cdietrich** 2018-10-26 08:30 UTC
