### ISSUE TITLE
update error when trying to install Xtext Complete SDK Version 2.17.1.v20190403-0733

### ISSUE THREAD

**Issue by neumaennl** [eclipse/xtext#1438] opened 2019-04-25 09:15 UTC
Eclipse shows me an update for the Xtext Complete SDK (Version 2.17.1.v20190403-0733), but when I try to install the update, I get the following error message: 

> An error occurred while collecting items to be installed session context was:(profile=C__eclipse_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=). No repository found containing: osgi.bundle,com.google.inject,3.0.0.v201605172100

**Comment by cdietrich** [comment] 2019-04-25 09:19
What is your base eclipse
And how can you have Xtext already installed with no guice

**Comment by cdietrich** [comment] 2019-04-25 09:27
@szarnekow @kthoms 
with what criteria do we decide what to repackage from orbit on
xtext-umrella/releng/org.eclipse.xtext.sdk.p2-repository/category.xml

**Comment by neumaennl** [comment] 2019-04-25 10:53
I have Eclipse IDE for Java Developers

Version: 2019-03 (4.11.0)
Build id: 20190314-1200


I think I installed Xtext from the Eclipse Marketplace, but I don't really remember anymore.

**Comment by neumaennl** [comment] 2019-04-25 10:54
> What is your base eclipse (version)
> And how can you have Xtext already installed with no guice?

I have Eclipse IDE for Java Developers

Version: 2019-03 (4.11.0)
Build id: 20190314-1200

I think I installed Xtext from the Eclipse Marketplace, but I don't really remember anymore.

**Comment by cdietrich** [comment] 2019-04-25 10:57
But which guice version do you have installed then

**Comment by cdietrich** [comment] 2019-04-25 13:30
I wonder which metadata want to have the newer one

**Comment by cdietrich** [comment] 2019-04-28 17:26
https://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.17.1/content.jar
does not contain `3.0.0.v201605172100` 

am not sure how the marketplace stuff is done.
do you @kthoms

**Comment by cdietrich** [comment] 2019-04-28 17:39
@kthoms i dont even find Xtext 2.17.x in Marketplace

**Comment by cdietrich** [comment] 2019-04-28 17:51
i tried to reproduce this issue @neumaennl 
- download 2019-03 java
- install Xtext 2.16 from Marketplace
- update to 2.17.0 from 2019-03 update site
- update to 2.17.1 from Xtext update site
=> works fine
=> i cannot reproduce your issue and need more details regarding the steps

**Comment by neumaennl** [comment] 2019-05-02 07:20
I've done nothing special, so I can't give you any steps to reproduce this. I can only describe what I did:
I installed Eclipse IDE for Java Developers version 4.8.0.v20180611-0656 on September 18th 2018 and I installed Xtext Complete SDK version 2.14.0.v20180523-0937 on September 19th. I've always installed all updates whenever there was a prompt informing me that there is a new update to install so that I am now on Eclipse version 4.11.0.v20190307-0500 and Xtext Complete SDK version 2.17.0.v20190304-1445. Now Eclipse shows me an update for the Xtext Complete SDK version 2.17.1.v20190403-0733, but when I try to install the update, I get the error message cited above.

There is nothing more that I can tell you. It would probably help if you could see my installation history, but I don't see a way to export this.

**Comment by cdietrich** [comment] 2019-05-06 06:13
i consider to close this as wontfix since i cannot reproduce
@szarnekow @kthoms @ArneDeutsch what do you think

**Closed** 2019-05-14 08:18 UTC

**Comment by neumaennl** [comment] 2019-06-03 06:30
FYI, the problem was somehow solved a few days ago and I was able to update.
