### ISSUE TITLE
Correct displayable data

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1328] opened 2018-11-06 13:53 UTC
Simrel tests are detecting issues with displayable data:
`Correct displayable data (checkLicenseConsistency,checkCopyrights,checkDescriptions)`

https://ci.eclipse.org/xtext/job/simrel-tests/10849/testReport/junit/org.eclipse.xtext.releng.simrel.tests/RepositoryTest/testFeatureDisplayableData/

**Comment by cdietrich** [comment] 2018-11-06 13:56
@kthoms i assume this is caused by the bad license feature change
=> we either need to revert these or merge the open pull requests that make use of the cbi 1.0 features

**Comment by cdietrich** [comment] 2018-11-09 08:34
is fixed nowhttps://ci.eclipse.org/xtext/job/simrel-tests/10863/

**Closed by cdietrich** 2018-11-09 08:34 UTC
