### ISSUE TITLE
Installing latest Xtext Version in Eclipse Photon

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#1234] opened 2018-07-04 10:49 UTC
When installing Xtext in the latest version from http://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest/ into Eclipse Photon I get the following error message:

![grafik](https://user-images.githubusercontent.com/20393472/42273136-9c75c842-7f88-11e8-8c43-96f9cfa9186b.png)

```
An error occurred while collecting items to be installed
session context was:(profile=com.genuitec.delivery.package.profile.6854-Dph-5026, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,org.eclipse.xtext,2.15.0.v20180628-0509.
SHA-256 hash is not as expected. Expected: 7a431357baabe7b1a787f9e3aa188270d665b84cd268c35507f07d2178c76fa5 and found 0b192af71bd668e74d3b759392a4c04e526f720e6563b50cf1ecfae434722b81.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.ui,2.15.0.v20180630-0924.
SHA-256 hash is not as expected. Expected: 4d5d8cb5e88dfa0e1e8e1a1775853cfae6246132ddaa2e52e5aa8b8ccabd59d6 and found 201dd60b3b7e5aaf671b62479a1446c6c7411b2ec15cba47bafd97a101ddee29.
Problems downloading artifact: osgi.bundle,org.eclipse.xtend.core,2.15.0.v20180628-1206.
SHA-256 hash is not as expected. Expected: 349bc979e077edb6f32ac159479a34666a8cd260cbcac8ee7eb9c80d44e56e88 and found c505ffe7e013c27e791d950f1c088f46220e83436eb5056fe6a676351cd09ad8.
Problems downloading artifact: osgi.bundle,org.eclipse.xtend.core.source,2.15.0.v20180628-1206.
SHA-256 hash is not as expected. Expected: f9eca9ea7a7cc622e24631728ae22eedf86f2a0a9cc35801084a36de1cc503dd and found 26d5fc24e415da5caf63e7cc9014410bd45d5f68b8b159458110b31142aaa9e3.
Problems downloading artifact: osgi.bundle,org.eclipse.xtend.doc,2.15.0.v20180628-1206.
SHA-256 hash is not as expected. Expected: 31a90d7c4b0d75bb1cab41d091311a59f557be7b49218794ab34ff0ff9e7ee4a and found b25759f7ba044dfa2175e401af1035bbd061fac27488a733a11ab27818170b41.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.doc,2.15.0.v20180630-0924.
SHA-256 hash is not as expected. Expected: d68a5f8abc900211606f4ec259478fa6cbb363d989b9ba3c6c5592b8b1f5a099 and found 8b6f55ad961b79032d0d6dd0e0281e3929b58d136495f54b944bd14fa17d7aa7.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.generator.source,2.15.0.v20180628-0524.
SHA-256 hash is not as expected. Expected: 84a9f7a128c2303bd2fb712db391823b269b19a74e0287292a96b4b6cdb60437 and found 11c5b8f5caab0bf950cf2257f387d9bd3c3d09ff453a6665883093556ede8e86.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.ide.source,2.15.0.v20180628-0509.
SHA-256 hash is not as expected. Expected: 0ffaddd8484c6d6054e24fa759527c7801e011dd11dfb5ec4efc8ea452fe5a8e and found 1c3c9bd6babfb28d5686ad13618043a37315576ddba5f52d87dfd3531f2a9866.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.source,2.15.0.v20180628-0509.
SHA-256 hash is not as expected. Expected: 89f1b8630384e3c0242cb66f19232311ae87d1b10fe4c3e8029be570ae75f77a and found 1f4e54f9355b058d930cd7343adb2e9d969f80ca17c051f7c948d084c3b3578e.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.ui.source,2.15.0.v20180630-0924.
SHA-256 hash is not as expected. Expected: b3f45542d50bfa65c83b8a039aab3e10998701251ff70653b9132963bc8a19f2 and found 67f3dec18896f779d4069c4cb44be45b20ff6cd7d531940da9cbb7be06d0d22b.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.xbase,2.15.0.v20180628-0524.
SHA-256 hash is not as expected. Expected: f5b69b243b86ecd62d6fec378ace3111ebdc75feede0ad606ebf47d8733bee87 and found a877ff824d3a49b147f5b41e6b3a78ae66768d9b7a0e089958daf348d0bf9c65.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.xbase.source,2.15.0.v20180628-0524.
SHA-256 hash is not as expected. Expected: d3d9e0f1076219fd1a6bfc8abbb0800c3d30c808ab0225b0627951a594e3cc5c and found d016241fb29b22b6c497c60c9e423d9aba8c6c81d128ee2748f7ad12712c51f5.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.xtext.generator,2.15.0.v20180628-0509.
SHA-256 hash is not as expected. Expected: 4936b1d1fc57bc54ca7acfe1236e86f58ba699ac410b6c8068f144c69287d931 and found 1d32abb5e94d06eae57f42cd15c30d331e05a41e63e78372f09ed30b5bd9ddb8.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.xtext.generator.source,2.15.0.v20180628-0509.
SHA-256 hash is not as expected. Expected: b5f49700b89131cecc0059ecb96bc0f2e0dc83b2349c846c4739836cd1f28740 and found ea3ec37d10e0b1c5fbae4d4d2641115fc7e9a3adfe26a118d207dfc99787a475.
Problems downloading artifact: osgi.bundle,org.eclipse.xtext.xtext.ui.examples,2.15.0.v20180630-0924.
SHA-256 hash is not as expected. Expected: c8c93c61eec6b7e685810df4e66ba986ac31d20817a10684e79a54711af5139f and found e7bb5c5e93c73f871211936cab05169efe3ef290323cd2d1e53bb6d65aa9d51a.
```

**Comment by cdietrich** [comment] 2018-07-04 10:51
for me this sounds like a dupe of https://github.com/eclipse/xtext/issues/1230 and should be fixed by now. the timestamp still looks a bit old.

=> maybe the chain has to be triggered once more completely through

**Comment by cdietrich** [comment] 2018-07-04 14:07
@miklossy please retest

**Comment by miklossy** [comment] 2018-07-05 05:20
Today in the morning I could successfully install Xtext in version 2.15.0.v20180704-1052.
Problem solved, ticket can be closed. Thx @cdietrich

**Closed** 2018-07-05 05:29 UTC
Labels: duplicate
