### ISSUE TITLE
Failure in Oomph setup when modifying .classpath files

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2110] opened 2022-11-09 09:15 UTC
I haven't been run the Oomph setup for a while. I've just tried that and I get a failure at this point:

```
Performing Text Modify configuration:/config.ini
Modifying file:/media/bettini/common/oomph/xtext-master/eclipse/configuration/config.ini
Performing Resource Creation file:/home/bettini/oomph/xtext-master/ws/.metadata/.plugins/org.eclipse.jdt.ui/dialog_settings.xml
Creating file:/home/bettini/oomph/xtext-master/ws/.metadata/.plugins/org.eclipse.jdt.ui/dialog_settings.xml
Performing Text Modify platform:/resource/org.eclipse.xtext.builder/.classpath
Modifying platform:/resource/org.eclipse.xtext.builder/.classpath
java.io.IOException: The path '/org.eclipse.xtext.builder/.classpath' is unmapped
```

**Comment by cdietrich** [comment] 2022-11-09 09:16
hmmmm i never saw this in the recent weeks.
dont you have org.eclipse.xtext.builder in workspace or .classpath deleted?

**Comment by LorenzoBettini** [comment] 2022-11-09 09:18
It's a brand new fresh setup so I had nothing yet cloned. I think those tasks should not be executed during the p2 provisioning but only after the projects have been cloned (and imported in the workspace)

**Comment by cdietrich** [comment] 2022-11-09 09:19
hmmm unfortunately i dont know oomph well enhough to have any clue where to look at.

**Comment by LorenzoBettini** [comment] 2022-11-09 09:21
If you try yourself from scratch you should get such an error yourself.
If that's the case for you as well, that's a kind of stopper. Of course, I managed to go on by disabling those tasks with the Oomph UI... let's see if the rest of workspace provisioning works...

**Comment by cdietrich** [comment] 2022-11-09 09:23
hmm the order looks ok to me

![Screenshot 2022-11-09 102250](https://user-images.githubusercontent.com/238736/200791452-cff4c16a-79c3-432f-ac2e-28a5e16296d8.png)

**Comment by LorenzoBettini** [comment] 2022-11-09 09:37
Maybe those tasks are required, because the workspace is full of errors... I'll try to run them again now that the projects are open in the workspace

**Comment by merks** [comment] 2022-11-09 09:39
It also fails for me like this:

![image](https://user-images.githubusercontent.com/208716/200793172-e7fa29d5-dc0d-4fcd-a06f-b07eaf186094.png)

So it's not just an ordering problem it's also a problem that these task are running in the installer, i.e., with bootstrap trigger.

By default all task run for all possible triggers.  Many tasks cannot run for bootstrap trigger but a Test Modify task can, so you need to disable that via the advanced properties.  This is how it will look currently:

![image](https://user-images.githubusercontent.com/208716/200794489-2d834810-c80e-484c-8c63-9b076a740b57.png)

You need to remove BOOTSTRAP:

![image](https://user-images.githubusercontent.com/208716/200794623-7b8503e4-3015-4ccb-b3bc-d9d1f58ba2e1.png)

For those inclined to edit the XML, this `excludedTriggers="BOOTSTRAP"` will appears in the serialization:
```
<?xml version="1.0" encoding="UTF-8"?>
<setup:TextModifyTask
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:setup="http://www.eclipse.org/oomph/setup/1.0"
    excludedTriggers="BOOTSTRAP"
    url="${github.clone.ecf.location|uri}/framework/bundles/org.eclipse.ecf.identity/src/org/eclipse/ecf/core/util/SystemLogService.java"
    encoding="UTF-8"/>
```

**Comment by LorenzoBettini** [comment] 2022-11-09 09:48
By the way, if I try to manually select them when performing tasks in the workspace it does not execute them anyway...

**Comment by cdietrich** [comment] 2022-11-09 09:51
but what has changed. i did setups on 5 machines 2 months ago and there does not seem to have been a problem

**Comment by merks** [comment] 2022-11-09 09:57
I don't believe anything has changed:

![image](https://user-images.githubusercontent.com/208716/200799442-7d86b060-5155-4fbe-9560-8f38cbb909c5.png)

The isNeeded is like this so will return true for a file that doesn't exist.
```
  @Override
  public boolean isNeeded(SetupTaskContext context) throws Exception
  {
    if (getURL() == null)
    {
      return false;
    }

    try
    {
      String text = getText(context);
      for (TextModification modification : getModifications())
      {
        Pattern pattern = Pattern.compile(modification.getPattern());
        Matcher matcher = pattern.matcher(text);
        if (matcher.find())
        {
          return true;
        }
      }

      return false;
    }
    catch (IOException exception)
    {
      // The file might not exist yet.
      return true;
    }
  }
```
And will fail when the file doesn't exist by the time the task is performed...

**Comment by cdietrich** [comment] 2022-11-09 09:59
i mean: the text modification is in our setup for 3 years now.
why does it fail now and not for the last 3 years

**Comment by merks** [comment] 2022-11-09 10:11
Sorry, I can't explain that.  I tested with an installer from 2021-12

https://download.eclipse.org/oomph/epp/2021-12/R/

And that also shows these tasks being triggered:

![image](https://user-images.githubusercontent.com/208716/200801643-f02ff41d-75c4-434c-bb0e-b2f4e748e853.png)

And if fails the same way.  So maybe you are reusing clones such that it doesn't fail but when the clone doesn't exist it fails and I expect to to fail.

**Comment by LorenzoBettini** [comment] 2022-11-09 11:06
Even with the things already cloned, it still fails: those are "platform:/resource" URIs, so I guess the projects must have already been imported into the workspace. The sources in place are not enough if I understand correctly.

**Comment by LorenzoBettini** [comment] 2022-11-09 11:19
@cdietrich I'm also having all gradle projects marked with errors because of

Invalid Gradle project configuration file: .settings/org.eclipse.buildship.core.prefs

whose contents are:

```
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=../../../../../../media/bettini/common/oomph/xtext-master/git/xtext-umbrella/releng/gradle-composite
project.path=\:xtext-core
```

**Comment by LorenzoBettini** [comment] 2022-11-09 11:26
Looks like I can solve this one, NOT by launching GenerateBuildshipPreferences.launch, but by refreshing the `gradle-composite` project with "Gradle" => "Refresh Gradle Project".

Now the file has been changed into:

```
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=../xtext-umbrella/releng/gradle-composite
eclipse.preferences.version=1
project.path=\:xtext-core
```

**Comment by cdietrich** [comment] 2022-11-09 11:50
@LorenzoBettini you you do any wired selections about git checkout etc?

**Comment by cdietrich** [comment] 2022-11-09 12:10
@merks  i dont see the triggers at all in the editor

<img width="1133" alt="Bildschirmfoto 2022-11-09 um 13 09 14" src="https://user-images.githubusercontent.com/238736/200826913-140d506e-de89-478d-8cce-4249be10d3fa.png">

**Comment by cdietrich** [comment] 2022-11-09 12:10
@LorenzoBettini i dont have any gradle problems at all when i fix the text modify for the eclipse part

**Comment by merks** [comment] 2022-11-09 12:15
Read carefully what I said before and look closely at parts highlighted in red in the picture, which I copy and paste below.  Note that double click will open the properties view.

By default all task run for all possible triggers.  Many tasks cannot run for bootstrap trigger but a Test Modify task can, so you need to disable that via the advanced properties.  This is how it will look currently:

![image](https://user-images.githubusercontent.com/208716/200794489-2d834810-c80e-484c-8c63-9b076a740b57.png)

**Comment by LorenzoBettini** [comment] 2022-11-09 13:01
> @LorenzoBettini you you do any wired selections about git checkout etc? normally all projects are next to each other and the gradle stuff works fine

No, I don't have any specific customization, I just choose the defaults of Oomph:

```
> tree -L 3
.
└── xtext-master
    ├── eclipse
    │   ├── ${maven.repo.local}
    │   ├── ${nonTestMavenRepo}
    │   ├── configuration
    │   ├── configuration.1667992035434
    │   ├── dropins
    │   ├── eclipse
    │   ├── eclipse.ini
    │   ├── icon.xpm
    │   ├── plugins
    │   └── readme
    ├── git
    │   ├── xtext-core
    │   ├── xtext-eclipse
    │   ├── xtext-extras
    │   ├── xtext-lib
    │   ├── xtext-maven
    │   ├── xtext-umbrella
    │   └── xtext-xtend
    └── ws
```

**Comment by cdietrich** [comment] 2022-11-09 13:25
then i have no clue what causes your gradle issue :(

**Comment by LorenzoBettini** [comment] 2022-11-09 13:46
The change to Xtext.setup fixes the task execution.
The Gradle preferences are still generated in the wrong way... I have to refresh them manually to fix them... maybe it's worthwhile to say that in the contribution guide. I guess this happens because I put everything in another partition and linked that. In any case, it should not happen, but I'm not going to mess with Gradle (which I honestly hate with all myself ;)

**Comment by cdietrich** [comment] 2022-11-09 14:32
@LorenzoBettini  as said: i cannot reproduce.
:(

**Comment by LorenzoBettini** [comment] 2022-11-09 14:50
Now, not even "Refresh Gradle Project" on the gradle-composite project seems to work: it fails due to existing compilation problems...

**Comment by cdietrich** [comment] 2022-11-09 16:25
* What went wrong:
Execution failed for task ':'xtext-lib':org.eclipse.xtend.lib:compileJava'.
> Compilation failed; see the compiler error output for details.

maybe you use bad java version. is there anything in log?

**Comment by LorenzoBettini** [comment] 2022-11-10 06:57
Sorry, I forgot to add this other information: it fails because xtext-lib contains compilation errors (it does not find some Java annotations)... it's a kind of "egg and chicken" situation: "Refreshing project" would fix the compilation errors, but it can't run because of compilation errors. The solution I found (and documented in the contributing guide) is to first reset xtext-lib with Git.

**Comment by cdietrich** [comment] 2022-11-10 06:58
can you please provide the stuff xtext-lib cannot find. as said to me it looks like a java version problem

**Comment by LorenzoBettini** [comment] 2022-11-10 07:01
I have a working workspace now. Later I'll try to create another one and see if I experience the same problem

**Comment by LorenzoBettini** [comment] 2022-11-10 08:01
I tried from scratch on another computer, this time, "oomph" is a directory in my home folder, not a link.

During the task that runs the launch configuration "GenerateBuildshipPreferences" I get this error in the console (the compilation problems I had also yesterday); I'm using Java 17:

```
Working Directory: /home/bettini/oomph/xtext-master/git/xtext-umbrella/releng/gradle-composite
Gradle user home: /home/bettini/.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 7.4.2
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: generatePrefs

includeBuild /home/bettini/oomph/xtext-master/git/xtext-lib
includeBuild /home/bettini/oomph/xtext-master/git/xtext-core
includeBuild /home/bettini/oomph/xtext-master/git/xtext-extras
includeBuild /home/bettini/oomph/xtext-master/git/xtext-xtend
> Task :'xtext-lib':org.eclipse.xtext.xbase.lib:compileJava UP-TO-DATE
> Task :'xtext-lib':org.eclipse.xtend.lib.macro:compileJava UP-TO-DATE

> Task :'xtext-lib':org.eclipse.xtend.lib:compileJava FAILED
/home/bettini/oomph/xtext-master/git/xtext-lib/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/DataProcessor.java:17: error: cannot find symbol
import org.eclipse.xtend.lib.macro.TransformationContext;
                                  ^
  symbol:   class TransformationContext
  location: package org.eclipse.xtend.lib.macro
/home/bettini/oomph/xtext-master/git/xtext-lib/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/DataProcessor.java:18: error: cannot find symbol
import org.eclipse.xtend.lib.macro.declaration.ClassDeclaration;
                                              ^
  symbol:   class ClassDeclaration
  location: package org.eclipse.xtend.lib.macro.declaration
/home/bettini/oomph/xtext-master/git/xtext-lib/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/DataProcessor.java:20: error: cannot find symbol
import org.eclipse.xtend.lib.macro.declaration.MutableClassDeclaration;
                                              ^
  symbol:   class MutableClassDeclaration
  location: package org.eclipse.xtend.lib.macro.declaration
/home/bettini/oomph/xtext-master/git/xtext-lib/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/DataProcessor.java:40: error: cannot access RegisterGlobalsParticipant
public class DataProcessor extends AbstractClassProcessor {
       ^
...
```

It continues with more than 100 errors.

The xtext-core projects have the corrected `.settings/org.eclipse.buildship.core.prefs`

```
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=../../xtext-umbrella/releng/gradle-composite
project.path=\:org.eclipse.xtext
```

All the other projects have no such a file (I guess due to the above errors the launch configuration does not go on), and so they are full of errors.

"Refresh Gradle Project" does not work because of the compilation errors.

The `gradle-composite`'s build.gradle has an error marker of the shape:

```
The supplied phased action failed with an exception.
A problem occurred configuring project ':'xtext-core''.
Execution failed for task ':'xtext-lib':org.eclipse.xtend.lib:compileJava'.
Compilation failed; see the compiler error output for details.
```

The trick of resetting the xtext-lib git repository does not help in this case. The xtext-lib projects will not compile since they miss the `.settings/org.eclipse.buildship.core.prefs` file. Such a file cannot be generated because these projects don't compile.

**Comment by cdietrich** [comment] 2022-11-10 08:12
but why are the files not there, they are checked in

org.eclipse.buildship.core.prefs should have been generated by the gradle task for generating prefs

**Comment by LorenzoBettini** [comment] 2022-11-10 08:20
As I said in my comment: those files are generated by the gradle task, but the gradle task stops because of compilation errors. As I said, it's an "egg and chicken problem".

And those files are NOT checked in anymore (they used to, IIRC, but now they are git ignored): https://github.com/eclipse/xtext-lib/blob/master/.gitignore#L7

I seem to remember they used to be checked in. If they are not anymore I'd guess that you would experience the problem yourself if you started from scratch.

**Comment by cdietrich** [comment] 2022-11-10 08:27
but why dont i see this issues on any machine ....

**Comment by LorenzoBettini** [comment] 2022-11-10 08:29
Even if you start from scratch?
Which project set do you select with Oomph?
All of them? (I skip only "Web")

**Comment by LorenzoBettini** [comment] 2022-11-10 08:31
With "Core" only if works, because it doesn't see compilation errors on xtext-lib projects that are not there.

**Comment by cdietrich** [comment] 2022-11-10 08:42
on windows i have another problem i did not see on mac

```Creating local branch master
java.lang.Exception: org.eclipse.jgit.api.errors.RefAlreadyExistsException: Ref master already exists
  at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.perform(GitCloneTaskImpl.java:974)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
```
@merks any idea?

**Comment by LorenzoBettini** [comment] 2022-11-10 08:47
> on windows i have another problem i did not see on mac
> 
> ```
> java.lang.Exception: org.eclipse.jgit.api.errors.RefAlreadyExistsException: Ref master already exists
>   at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.perform(GitCloneTaskImpl.java:974)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
>   at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
>   at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
> ```
> 
> @merks any idea?

I had the same problem yesterday if I selected 2022-12 as the Eclipse version. Using 2022-09 fixed the problem for me

**Comment by cdietrich** [comment] 2022-11-10 08:48
so there seems to be a problem with latest jgit 2022-10-26 @merks  is this a known oomph issue?

**Comment by LorenzoBettini** [comment] 2022-11-10 08:48
> With "Core" only if works, because it doesn't see compilation errors on xtext-lib projects that are not there.

If I then add "Extras" it works (though there are error markers on the old xtext.generator project because it can't find old Xtend/Xpand

**Comment by cdietrich** [comment] 2022-11-10 08:49
i dont get this point. xpand comes from the bom in lib.

**Comment by LorenzoBettini** [comment] 2022-11-10 08:58
Remember: I'm trying this new experiment: 

- Start from scratch by selecting only "Core" -> it works
- Then, using the Oomph menu, "Import Projects...", I select also "Extras" -> it works
- Then, with the same menu, I select also "Xbase/Xtend Libraries (i.e., "xtext-lib") -> IT WORKS!

So it looks like xtext-lib needs all its dependencies (core and xbase) be already compiled.

If I select the three projects together I get the problem with xtext-lib.

My guess is that it's due to a synchronization problem.

In any case, the generation of buildship preferences should start from xtext-core, then xtext-extras (if it's there) and then xtext-lib (if it's there). If xtext-extras has not been compiled, then xtext-lib cannot be compiled. If xtext-lib cannot be compiled, gradle fails generating the preferences.

**Comment by merks** [comment] 2022-11-10 09:02
The jgit behavior change was accommodated in Oomph, but only the nightly build installer sees the fix, until I do a milestone build for M3, then the regular installers will install the fix.  This describes the problem and has a link to the nightly installers.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=580968#c3

Note that one can replicate/test the "brand new user never before did any Eclipse thing" by running the installer with `-vmargs -Duser.home=<some-folder> -Doomph.setup.user.home.redirect=true`.  I use that to test the locally-built installers:

![image](https://user-images.githubusercontent.com/208716/201045620-cd4a55ad-6b21-41fe-9591-6ebc1c14ada5.png)

This will use the specifed `<some-folder>` as home and the `-Doomph.setup.user.home.redirect` tells the installer to generate a `-Duser.home=<some-folder>` in the eclipse.ini of the installation.   You can delete <some-folder> anytime later because everything (e.g., the .p2 folder with the pool, and the .eclipse folder with other stuff) will be self container in that folder.

**Comment by merks** [comment] 2022-11-10 09:06
> Indeed, the Oomph setup should never process "Xbase/Xtend Libraries" before "Extras", otherwise xtext-lib cannot find dependencies from xtext-extras.
> 
> The Oomph setup seems to list them in the wrong order:
> 
> @merks I guess Oomph keeps the order of subprojects into consideration during the setup, right?

I believe so, yes.

**Comment by LorenzoBettini** [comment] 2022-11-10 09:08
@merks Thanks! Then I guess the order is wrong.

@cdietrich the only other thing that is surely different on my machine with respect to yours is that both today and yesterday I started with a completely empty ".gradle" directory. I guess you have a .gradle directory with lots of (Xtext) artifacts already in there.

**Comment by LorenzoBettini** [comment] 2022-11-10 09:18
@cdietrich I try to rearrange the tasks locally and start from scratch and see if that solves the problem

**Comment by cdietrich** [comment] 2022-11-10 09:34
i still dont see the dependency from lib to core and extras

**Comment by LorenzoBettini** [comment] 2022-11-10 09:42
> on my windows it works find with fresh location

and starting with an empty `.gradle` folder?

**Comment by cdietrich** [comment] 2022-11-10 09:44
![Screenshot 2022-11-10 104343](https://user-images.githubusercontent.com/238736/201056581-9d481e6e-1970-4ffa-b6e9-a94855e84e93.png)

order on my machine.
with gradle you mean home/.gradle?

**Comment by cdietrich** [comment] 2022-11-10 09:50
will try eds user home redirect

**Comment by LorenzoBettini** [comment] 2022-11-10 09:50
> i still dont see the dependency from lib to core and extras

You're right about that. However, I guess that the Xtend compiler in the installed Eclipse kicks in fast and regenerates the xtend-gen contents of xtext-lib projects with errors (since it cannot find required stuff from Xbase?) making the projects of xtext-lib not compilable, breaking the workflow.

I confirm that, starting from scratch (even with empty .gradle and .m2 folder) by reordering the tasks in the setup file everything works.

I'll submit a patch.

**Comment by cdietrich** [comment] 2022-11-10 09:52
the question is how to test that patch....

**Comment by LorenzoBettini** [comment] 2022-11-10 10:00
> the question is how to test that patch....

Like I did with yours: download the patched "Xtext.setup" locally, with Oomph, add a "user project" (select the downloaded Xtext.setup) and start with that.

**Comment by cdietrich** [comment] 2022-11-10 10:05
yes but as i never have a problem how to know if it fixes anything

**Comment by LorenzoBettini** [comment] 2022-11-10 10:10
Just to make sure: have you tried with an empty home/.gradle directory before?

At least, you can try it doesn't break anything ;)

In Linux I can confirm:

- it doesn't work with the current setup
- it works with my patched version both when starting with an empty .gradle directory and when starting with an existing .gradle directory

**Comment by cdietrich** [comment] 2022-11-10 10:14
maybe i care too much about understanding why :(

**Comment by LorenzoBettini** [comment] 2022-11-10 10:24
Another experiment I've just done:

Now that all the gradle dependencies are in place, I tested again the current Xtext.setup (NOT my patched version) and it works. So to fully reproduce the original problem, having a prefilled .gradle directory (with all the Xtext dependencies already there) is NOT enough.

I think it's good to understand why.

I repeat my possible explanation: "I guess the Xtend compiler in the installed Eclipse kicks in fast and regenerates the xtend-gen contents of xtext-lib projects with errors (since it cannot find required stuff from Xbase?), making the projects of xtext-lib not compilable, breaking the workflow."

This happens if you start with an empty .gradle directory.
It does NOT happen with a .gradle directory with all the dependencies.
In such a case, the Xtend compiler does NOT generate xtend-gen contents with errors.

My Xtext.setup works both with an empty .gradle directory and with an existing one. At least in my experiments.

If you want, I can do further experiments later.

**Comment by cdietrich** [comment] 2022-11-10 10:28
for me it also works with empty gradle home (just the expected compile errors in xtend, as gradle stuff has not been installed to local maven .m2 and i removed this one as well.

here is my log 
[oomphlog-emptygradle.txt](https://github.com/eclipse/xtext/files/9979810/oomphlog-emptygradle.txt)

**Comment by LorenzoBettini** [comment] 2022-11-10 10:38
So what's left to test is if my version also works on Windows and on macOS.

**Comment by cdietrich** [comment] 2022-11-10 10:51
also just selecting core and libs works fine for me (with empty .gradle), does this still fail for you?

**Comment by cdietrich** [comment] 2022-11-10 11:02
=> now i seem to have the problem you have
=> problem is not understood.

**Comment by cdietrich** [comment] 2022-11-10 11:04
i also can find this in the logs
```
Working Directory: C:\lalaxxx3\xtext-master\git\xtext-umbrella\releng\gradle-composite
Gradle user home: C:\lalaxxx3\.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 7.4.2
Java Home: C:\lalaxxx3\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.5.v20221102-0933\jre
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: generatePrefs

includeBuild C:\lalaxxx3\xtext-master\git\xtext-lib
includeBuild C:\lalaxxx3\xtext-master\git\xtext-core
includeBuild C:\lalaxxx3\xtext-master\git\xtext-extras
> Task :'xtext-lib':org.eclipse.xtext.xbase.lib:compileJava UP-TO-DATE
> Task :'xtext-lib':org.eclipse.xtend.lib.macro:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':'xtext-lib':org.eclipse.xtend.lib.macro:compileJava'.
> Unable to delete directory 'C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org
    New files were found. This might happen because a process is still writing to the target directory.
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\services
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\services\AnnotationReferenceBuildContext.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\file
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\file\Path.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\file\Path$1.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\expression
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\expression\Expression.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration\VoidType.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration\Visibility.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration\TypeReference.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration\TypeParameterDeclarator.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration\TypeParameterDeclaration.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration\ResolvedTypeParameter.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration\ResolvedParameter.class
    - C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib.macro\build\classes\java\main\org\eclipse\xtend\lib\macro\declaration\ResolvedMethod.class
    - and more ...

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
2 actionable tasks: 1 executed, 1 up-to-date

```

**Comment by cdietrich** [comment] 2022-11-10 11:05
maybe something that en- or disable autobuild in oomph is no longer working.

**Comment by LorenzoBettini** [comment] 2022-11-10 11:12
> @LorenzoBettini with your change i get on windows
> 
> ```
> Working Directory: C:\lalaxxx3\xtext-master\git\xtext-umbrella\releng\gradle-composite
> Gradle user home: C:\lalaxxx3\.gradle
> Gradle Distribution: Gradle wrapper from target build
> Gradle Version: 7.4.2
> Java Home: C:\lalaxxx3\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.5.v20221102-0933\jre
> JVM Arguments: None
> Program Arguments: None
> Build Scans Enabled: false
> Offline Mode Enabled: false
> Gradle Tasks: generatePrefs
> 
> includeBuild C:\lalaxxx3\xtext-master\git\xtext-lib
> includeBuild C:\lalaxxx3\xtext-master\git\xtext-core
> includeBuild C:\lalaxxx3\xtext-master\git\xtext-extras
> includeBuild C:\lalaxxx3\xtext-master\git\xtext-web
> includeBuild C:\lalaxxx3\xtext-master\git\xtext-xtend
> > Task :'xtext-lib':org.eclipse.xtext.xbase.lib:compileJava UP-TO-DATE
> > Task :'xtext-lib':org.eclipse.xtend.lib.macro:compileJava UP-TO-DATE
> 
> > Task :'xtext-lib':org.eclipse.xtend.lib:compileJava FAILED
> C:\lalaxxx3\xtext-master\git\xtext-lib\org.eclipse.xtend.lib\xtend-gen\org\eclipse\xtend\lib\annotations\AccessorsProcessor.java:19: error: cannot find symbol
> import org.eclipse.xtend.lib.macro.TransformationContext;
>                                   ^
> ```

With my setup it fails for you on Windows?
That's strange, I'm going to try that now.
I guess that when this fails, your xtext-lib projects have all changes in the xtend-gen folder, right?

**Comment by LorenzoBettini** [comment] 2022-11-10 11:12
> maybe something that en- or disable autobuild in oomph is no longer working. or we are not properly waiting for the gradle launch configs that are called during the build unfortunately i know too few about oomph ....
> 
> on mac i dont see this issue ....

@merks is there a way to disable automatic building during the workspace setup?

**Comment by LorenzoBettini** [comment] 2022-11-10 11:35
> for me it also works with empty gradle home (just the expected compile errors in xtend, as gradle stuff has not been installed to local maven .m2 and i removed this one as well.
> 
> here is my log [oomphlog-emptygradle.txt](https://github.com/eclipse/xtext/files/9979810/oomphlog-emptygradle.txt)

What looks good in your log is that the buildship preferences are generated BEFORE importing the projects in the workspace.

I've just tried on Windows, starting from scratch and it works with the original Xtext.setup. Everything is much slower in Windows. And I cannot see any "compileJava" task in my log (it appears in yours instead). I'm wondering what gradle does...

Later, I'll try my setup on Windows as well.

**Comment by cdietrich** [comment] 2022-11-10 13:05
build automatically seems off, but i am not sure if import and gradle stuff dont run in parallel in setup

**Comment by cdietrich** [comment] 2022-11-10 13:07
![Screenshot 2022-11-10 140621](https://user-images.githubusercontent.com/238736/201099469-92398108-2bd6-40c6-9b12-e80f83906f08.png)

**Comment by LorenzoBettini** [comment] 2022-11-10 13:44
Is the launch configured to be executed in background?

**Comment by cdietrich** [comment] 2022-11-10 13:49
looks like. am currently testing

https://github.com/eclipse/xtext-umbrella/compare/cd_tralalala

**Comment by cdietrich** [comment] 2022-11-10 13:51
=> wonder if the original setup works for you if you use

```
  <setupTask
      xsi:type="git:GitCloneTask"
      id="git.clone.xtext.umbrella"
      remoteURI="eclipse/xtext-umbrella"
      pushURI=""
      checkoutBranch="cd_tralalala">
```
there

**Comment by LorenzoBettini** [comment] 2022-11-10 14:15
@cdietrich I confirm that on Windows, my setup gives the same problems on xtext-lib as you experienced (which in Linux I was experiencing with the original setup file). On Windows, the original setup file works...

I'll try your branch with the change in a local Xtext.setup (starting from the original one of course).

I'll try that on Windows and Linux...

**Comment by LorenzoBettini** [comment] 2022-11-10 14:59
@cdietrich in Windows (starting again from scratch) using your branch as you suggested works.
Although in Windows it was working also before (with the original Xtext.setup) in the log I now see

```
Configure project :'xtext-lib':org.eclipse.xtext.dev-bom
Configure project :'xtext-core'
Task :'xtext-lib':org.eclipse.xtext.xbase.lib:compileJava
Task :'xtext-lib':org.eclipse.xtend.lib.macro:compileJava
Task :'xtext-lib':org.eclipse.xtend.lib:compileJava
Task :'xtext-lib':org.eclipse.xtend.lib.macro:configureManifest
Configure project :'xtext-core'
Configure project :'xtext-core':org.eclipse.xtext.ide.tests
Performing Projects Import
```

which makes me think that there's much more synchronization: the projects are imported when gradle finished its job.

Now I'll check that with Linux

**Comment by LorenzoBettini** [comment] 2022-11-10 15:33
@cdietrich I confirm that it also works in Linux (I started from scratch with empty .gradle and .m2)! :)

I see a diff (I forgot to mention that I've always seen it, also in Windows):

![image](https://user-images.githubusercontent.com/1202254/201137504-a0a36898-d8e2-439e-bda9-378b69d79da5.png)

is that expected? I seem to understand that files `org.eclipse.buildship.core.prefs` are excluded by .gitignore.

**Comment by cdietrich** [comment] 2022-11-10 15:46
Yes and no. I guess one we need. Might be a change due newer buildship version

**Comment by LorenzoBettini** [comment] 2022-11-10 16:50
> Yes and no. I guess one we need. Might be a change due newer buildship version

Do you mean I should commit the changed version?

**Comment by cdietrich** [comment] 2022-11-10 17:10
see https://github.com/eclipse/xtext-umbrella/pull/336

**Comment by cdietrich** [comment] 2022-11-11 08:10
@LorenzoBettini anything left?

**Comment by LorenzoBettini** [comment] 2022-11-11 09:02
@cdietrich I'd say that we're all fine now! Thanks!

**Closed** 2022-11-11 09:06 UTC
Labels: help_wanted
